#!/bin/sh

DESTDIR=/usr/local/bin
find bin -type f -print -exec install {} $DESTDIR/ \;

if [ -L $DESTDIR/colordiffbin ] ; then
    rm $DESTDIR/colordiffbin
fi    
ln -s $DESTDIR/diffbin $DESTDIR/colordiffbin 
