#!/bin/sh

DESTDIR=/usr/local/bin
find bin -type f -print -exec install {} $DESTDIR/ \;

if [ -L $DESTDIR/colordiffbin ] ; then
    rm $DESTDIR/colordiffbin
fi    
ln -s $DESTDIR/diffbin $DESTDIR/colordiffbin 

if [ -L $DESTDIR/emu_util_stlink ] ; then
    rm $DESTDIR/emu_util_stlink
fi 
ln -s $DESTDIR/emu_util $DESTDIR/emu_util_stlink

if [ -L $DESTDIR/emu_util_cmsisdap ] ; then
    rm $DESTDIR/emu_util_cmsisdap
fi 
ln -s $DESTDIR/emu_util $DESTDIR/emu_util_cmsisdap

if [ -L $DESTDIR/emu_util_openocd ] ; then
    rm $DESTDIR/emu_util_openocd
fi 
ln -s $DESTDIR/emu_util $DESTDIR/emu_util_openocd


if [ -L $DESTDIR/analysis_mapfile_gui.py ] ; then
    rm $DESTDIR/analysis_mapfile_gui.py
fi 
ln -s $DESTDIR/analysis_mapfile.py $DESTDIR/analysis_mapfile_gui.py


