if [ `uname` = 'FreeBSD' ]; then
    alias ls='ls -G'
fi

alias l='ls'
alias la='ls -a'
alias ll='ls -l'
alias vi='vim'
alias vi.='vim .'
alias v='vim'
alias v.='vim .'
alias e='emacs'
alias e.='emacs .'
alias mktags='ctags -R'
alias cal3='cal -3'
alias du='du -h'
alias df='df -h'
alias dpython='python -m pdb'
alias lstty='ls /dev/tty*'
alias lsttyusb='ls /dev/ttyUSB*'
alias du.sort.less='du -h | sort -h | less +G'
alias miniterm.s0='miniterm.py /dev/ttyS0'
alias miniterm.0='miniterm.py /dev/ttyUSB0'
alias miniterm.1='miniterm.py /dev/ttyUSB1'
alias miniterm.2='miniterm.py /dev/ttyUSB2'
alias miniterm.3='miniterm.py /dev/ttyUSB3'
alias miniterm.4='miniterm.py /dev/ttyUSB4'
alias miniterm.5='miniterm.py /dev/ttyUSB5'
alias miniterm.6='miniterm.py /dev/ttyUSB6'
alias miniterm.7='miniterm.py /dev/ttyUSB7'
alias miniterm.8='miniterm.py /dev/ttyUSB8'
alias miniterm.9='miniterm.py /dev/ttyUSB9'

alias st-utild='repeat_run st-util'

alias git.commit.edit='git commit -am "edit"'
alias git.push='git push'
alias git.pull='git pull'
alias git.status='git status'



alias weather.shanghai="wget -O - http://www.weather.com.cn/weather/101020100.shtml | html2text | less"
alias wiki='elinks http://en.wikipedia.org/wiki/Main_Page#p-search'
alias pyscheme='python -c "import pyscheme; pyscheme.scheme.repl()"'

export EDITOR=vi
#export PATH=$PATH:/opt/rtems-4.11/bin
#export PATH=$PATH:$DIR_UTILS
#export PATH=$PATH:$DIR_UTILS/arm-2012.03/bin
#export PATH=$PATH:$DIR_UTILS/devkitpro/devkitARM/bin
#export PATH=$PATH:$DIR_UTILS/android-sdk-linux/platform-tools
#export PATH=$PATH:$DIR_UTILS/android-sdk-linux/tools
#export AP_PORT=9999


test -f ~/.extrarc && source ~/.extrarc

