if [ `uname` = 'FreeBSD' ]; then
    alias ls='ls -G'
fi

alias l='ls --color=auto'
alias la='ls -a --color=auto'
alias ll='ls -l --color=auto'
alias lla='ls -l -a --color=auto'
alias lh='ls -l -h --color=auto'
alias lha='ls -l -h -a --color=auto'
alias vi='vim'
alias vi.='vim .'
alias v='vim'
alias v.='vim .'
alias nv='nvim'
alias e='emacs'
alias e.='emacs .'
#alias mktags='ctags -R && etags -R'
alias mktags='ctags -R'
alias rmtags='rm -f tags TAGS'
alias cal3='cal -3'
alias du='du -h'
alias df='df -h'
alias dpython='python -m pdb'
alias lstty='ls /dev/tty[AU]*'
alias lstty2='lsttybyid'
alias lsttybyid="ls -l -o /dev/serial/by-id | awk '{n=split(\$10,sn,\"tty\"); if(n>1) print sn[2] \"\t\" \$8}' | sort"
alias du.sort.less='du -h | sort -h | less +G'
alias rr='repeat_run'

alias mts0='miniterm.py /dev/ttyS0'
alias mts1='miniterm.py /dev/ttyS1'
alias mts2='miniterm.py /dev/ttyS2'
alias mts3='miniterm.py /dev/ttyS3'
alias mts4='miniterm.py /dev/ttyS4'
         
alias mt0='miniterm.py /dev/ttyUSB0'
alias mt1='miniterm.py /dev/ttyUSB1'
alias mt2='miniterm.py /dev/ttyUSB2'
alias mt3='miniterm.py /dev/ttyUSB3'
alias mt4='miniterm.py /dev/ttyUSB4'
alias mt5='miniterm.py /dev/ttyUSB5'
alias mt6='miniterm.py /dev/ttyUSB6'
alias mt7='miniterm.py /dev/ttyUSB7'
alias mt8='miniterm.py /dev/ttyUSB8'
alias mt9='miniterm.py /dev/ttyUSB9'

alias mta0='miniterm.py /dev/ttyACM0'
alias mta1='miniterm.py /dev/ttyACM1'
alias mta2='miniterm.py /dev/ttyACM2'
alias mta3='miniterm.py /dev/ttyACM3'
alias mta4='miniterm.py /dev/ttyACM4'
alias mta5='miniterm.py /dev/ttyACM5'
alias mta6='miniterm.py /dev/ttyACM6'
alias mta7='miniterm.py /dev/ttyACM7'
alias mta8='miniterm.py /dev/ttyACM8'
alias mta9='miniterm.py /dev/ttyACM9'

alias mtr0='miniterm.py /dev/rfcomm0'
alias mtr1='miniterm.py /dev/rfcomm1'
alias mtr2='miniterm.py /dev/rfcomm2'
alias mtr3='miniterm.py /dev/rfcomm3'
alias mtr4='miniterm.py /dev/rfcomm4'
alias mtr5='miniterm.py /dev/rfcomm5'
alias mtr6='miniterm.py /dev/rfcomm6'
alias mtr7='miniterm.py /dev/rfcomm7'
alias mtr8='miniterm.py /dev/rfcomm8'
alias mtr9='miniterm.py /dev/rfcomm9'

alias mtR0='miniterm.py /dev/shm/ttyRemote0'
alias mtR1='miniterm.py /dev/shm/ttyRemote1'
alias mtR2='miniterm.py /dev/shm/ttyRemote2'
alias mtR3='miniterm.py /dev/shm/ttyRemote3'
alias mtR4='miniterm.py /dev/shm/ttyRemote4'
alias mtR5='miniterm.py /dev/shm/ttyRemote5'
alias mtR6='miniterm.py /dev/shm/ttyRemote6'
alias mtR7='miniterm.py /dev/shm/ttyRemote7'
alias mtR8='miniterm.py /dev/shm/ttyRemote8'
alias mtR9='miniterm.py /dev/shm/ttyRemote9'




alias mk='make'
alias mkc='make clean'
alias mkf='make flash'
alias mkr='make reset'
alias rmk='make clean && make'

alias sc='scons'
alias scc='scons -c'
alias src='scons -c && scons'
alias scca='DEBUG=1 scons -c && DEBUG=0 scons -c'
alias sca='DEBUG=1 scons -c && DEBUG=1 scons && DEBUG=0 scons -c && DEBUG=0 scons'

alias st-utild='REPEAT_DELAY=0.2 repeat_run st-util'
alias sshx='ssh -X'


alias rmswp='find ~ /data -name "*.swp" -print -delete'

alias git.commit.edit='git commit -am "edit"'
alias git.push='git push'
alias git.pull='git pull'
alias git.status='git status'
alias gits='git status'

alias setenv.sim='export SIM=1'
alias setenv.dev='export DEVELOPMENT=1'
alias setenv.debug='export DEBUG=1'
alias setenv.nodebug='export NODEBUG=1'
alias arm-none-eabi-gdbtui='arm-none-eabi-gdb --tui'
alias arm-none-eabi-cgdb='cgdb -d arm-none-eabi-gdb'

alias grep='grep --color=always'

alias weather.shanghai="wget -O - http://www.weather.com.cn/weather/101020100.shtml | html2text | less"
alias wiki='elinks http://en.wikipedia.org/wiki/Main_Page#p-search'
alias pyscheme='python -c "import pyscheme; pyscheme.scheme.repl()"'

export EDITOR=vi
#export PATH=$PATH:/opt/rtems-4.11/bin
#export PATH=$PATH:$DIR_UTILS
#export PATH=$PATH:$DIR_UTILS/arm-2012.03/bin
#export PATH=$PATH:$DIR_UTILS/devkitpro/devkitARM/bin
#export PATH=$PATH:$DIR_UTILS/android-sdk-linux/platform-tools
#export PATH=$PATH:$DIR_UTILS/android-sdk-linux/tools
#export AP_PORT=9999

export GOPATH='/home/trees/go/'
export GOROOT='/usr/local/go'


test -f ~/.extrarc && source ~/.extrarc

