if [ `uname` = 'FreeBSD' ]; then
    alias ls='ls -G'
fi

alias l='ls'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -l -a'
alias lh='ls -l -h'
alias lha='ls -l -h -a'
alias vi='vim'
alias vi.='vim .'
alias v='vim'
alias v.='vim .'
alias nv='nvim'
alias e='emacs'
alias e.='emacs .'
#alias mktags='ctags -R && etags -R'
alias mktags='ctags -R'
alias rmtags='rm -f tags TAGS'
alias cal3='cal -3'
alias du='du -h'
alias df='df -h'
alias dpython='python -m pdb'
alias lstty='ls /dev/tty*'
alias llserial='ll /dev/serial/by-id'
alias du.sort.less='du -h | sort -h | less +G'
alias mts0='miniterm.py /dev/ttyS0'
alias mt0='miniterm.py /dev/ttyUSB0'
alias mt1='miniterm.py /dev/ttyUSB1'
alias mt2='miniterm.py /dev/ttyUSB2'
alias mt3='miniterm.py /dev/ttyUSB3'
alias mt4='miniterm.py /dev/ttyUSB4'
alias mt5='miniterm.py /dev/ttyUSB5'
alias mt6='miniterm.py /dev/ttyUSB6'
alias mt7='miniterm.py /dev/ttyUSB7'
alias mt8='miniterm.py /dev/ttyUSB8'
alias mt9='miniterm.py /dev/ttyUSB9'
alias mta0='miniterm.py /dev/ttyACM0'
alias mta1='miniterm.py /dev/ttyACM1'
alias mta2='miniterm.py /dev/ttyACM2'
alias mta3='miniterm.py /dev/ttyACM3'
alias mta4='miniterm.py /dev/ttyACM4'
alias mta5='miniterm.py /dev/ttyACM5'
alias mta6='miniterm.py /dev/ttyACM6'
alias mta7='miniterm.py /dev/ttyACM7'
alias mta8='miniterm.py /dev/ttyACM8'
alias mta9='miniterm.py /dev/ttyACM9'
alias ev='evince'


alias sc='scons'
alias scc='scons -c'
alias src='scons -c && scons'
alias scca='DEBUG=1 scons -c && DEBUG=0 scons -c'
alias sca='DEBUG=1 scons -c && DEBUG=1 scons && DEBUG=0 scons -c && DEBUG=0 scons'

alias st-utild='REPEAT_DELAY=0.2 repeat_run st-util'
alias sshx='ssh -X'

alias remake='make clean && make'

alias rmswp='find ~ /data -name "*.swp" -print -delete'

alias git.commit.edit='git commit -am "edit"'
alias git.push='git push'
alias git.pull='git pull'
alias git.status='git status'

alias setenv.sim='export SIM=1'
alias setenv.dev='export DEVELOPMENT=1'
alias setenv.debug='export DEBUG=1'
alias setenv.nodebug='export NODEBUG=1'
alias arm-none-eabi-gdbtui='arm-none-eabi-gdb --tui'

alias grep='grep --color=always'

alias weather.shanghai="wget -O - http://www.weather.com.cn/weather/101020100.shtml | html2text | less"
alias wiki='elinks http://en.wikipedia.org/wiki/Main_Page#p-search'
alias pyscheme='python -c "import pyscheme; pyscheme.scheme.repl()"'

export EDITOR=vi
#export PATH=$PATH:/opt/rtems-4.11/bin
#export PATH=$PATH:$DIR_UTILS
#export PATH=$PATH:$DIR_UTILS/arm-2012.03/bin
#export PATH=$PATH:$DIR_UTILS/devkitpro/devkitARM/bin
#export PATH=$PATH:$DIR_UTILS/android-sdk-linux/platform-tools
#export PATH=$PATH:$DIR_UTILS/android-sdk-linux/tools
#export AP_PORT=9999

test -f ~/.extrarc && source ~/.extrarc

